baseURL = "https://remoteworlds.com/"
languageCode = "en-us"
title = "remote worlds"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  category = "categories"
paginate = 10
